[project]
name = "hl7-sender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "pydantic>=2.11.7",
    "streamlit>=1.46.1",
    "watchdog>=6.0.0",
]
